#define PLOOPY_DPI_OPTIONS {800}
#define PLOOPY_DPI_DEFAULT 0
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 8.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 8.0
#define PLOOPY_DRAGSCROLL_INVERT false
